version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app/nextjs-blog
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
